package io.kotlintest

class TestFailedException(reason: String) : RuntimeException(reason)